services:
    wh_recaptcha.validator:
        class: WH\RecaptchaBundle\Services\RecaptchaValidator
        autowire: true
    wh_recaptcha.register_parameter.twig_extension:
        class: WH\RecaptchaBundle\Twig\RegisterParameterExtension
        autowire: true
        public: false
        tags:
            - { name: twig.extension }
    wh_recaptcha.form.recaptcha:
        class: WH\RecaptchaBundle\Form\RecaptchaType
        arguments: ['@service_container']
        tags: [form.type]